### ISSUE TITLE
Novel view

### ISSUE THREAD

**Issue by ggfresh** [facebookresearch/audio2photoreal#34]
Awesome project! Where could I set the camera params for rendering novel view?

**Comment by evonneng** [comment]
Hi, thanks!! For the camera params, you could change the `K` and `Rt` matrix that is getting passed into the renderer. 

So for instance, I am just loading in some default camera parameters as per this line here: 
https://github.com/facebookresearch/audio2photoreal/blob/548aeeb2057465045ca1568d65ea059cea633d80/visualize/render_codes.py#L89

And passing in the parameters to the model here
https://github.com/facebookresearch/audio2photoreal/blob/548aeeb2057465045ca1568d65ea059cea633d80/visualize/render_codes.py#L121

This is where these things get ingested. https://github.com/facebookresearch/audio2photoreal/blob/548aeeb2057465045ca1568d65ea059cea633d80/visualize/ca_body/models/mesh_vae_drivable.py#L283-L285

Since different parts of the body decoder use either the K or the Rt, you will need to set both. Hope this helps!

**Comment by alexanderrichard** [comment]
Closing this issue as it seems resolved. Please reopen if you have more questions.
